FROM ghcr.io/home-assistant/base:latest

RUN apk add --no-cache \
    python3 \
    py3-pip

COPY requirements.txt /tmp/

RUN pip3 install --no-cache-dir --break-system-packages \
    -r /tmp/requirements.txt

COPY app /app
COPY run.sh /

RUN chmod a+x /run.sh

CMD [ "/run.sh" ]